### ISSUE TITLE
Question: Extracting project level meta data

### ISSUE THREAD

**Issue by johandahlberg** [MultiQC/MultiQC_Clarity#12]
I've been trying to pull meta data to put into the MultiQC header, but looking at the code here: https://github.com/MultiQC/MultiQC_Clarity/blob/d55ae4fddc3d819d4a65d8d6b41adbf3957d1501/multiqc_clarity/multiqc_clarity.py#L107-L119 I am a little confused. It seems to me that it tries to extract udfs on a sample rather than on a project level. In my case it appears that  `sample.project.udf` is always empty, which leads me to wonder if this is working as expected. I don't feel confident enough the know if this is due to differences in how our Clarity instances are configured, if I am misunderstanding something, or if this is a bug in the code here. I'd love the hear you folks input on this.

**Comment by ewels** [comment]
Maybe @Galithil is in a nice mood and can remember something about how this works..?

**Comment by johandahlberg** [comment]
Never mind. I figured this out. It was that the particular project that I was using for this didn't have any udfs set.

**Comment by ewels** [comment]
That would do it 😆
